# database
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/blog_example?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

oauth2:
  kakao:
    client-id: 69779556a1e86bbc4883911ac6062eb8
    client-secret: tm0oPlUDEyltKNYEpcjvtse5PGmPz5T5